### ISSUE TITLE
When I reproduce this code with Panasonic battery data, he has the following error.

### ISSUE THREAD

**Issue by swh851168382** [TL-UESTC/TATN#1]
H:\anaconda3\python.exe "G:\研究生论文\OneDrive - stu.hebut.edu.cn\TATN-main\normalized_data\process.py" 
Traceback (most recent call last):
  File "H:\anaconda3\lib\site-packages\scipy\io\matlab\_mio.py", line 39, in _open_file
    return open(file_like, mode), True
PermissionError: [Errno 13] Permission denied: 'G:\\研究生论文\\OneDrive - stu.hebut.edu.cn\\TATN-main\\normalized_data\\Panasonic 18650PF Data/-10degC'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\研究生论文\OneDrive - stu.hebut.edu.cn\TATN-main\normalized_data\process.py", line 154, in <module>
    read_and_save(path)
  File "G:\研究生论文\OneDrive - stu.hebut.edu.cn\TATN-main\normalized_data\process.py", line 15, in read_and_save
    data = sio.loadmat(file)
  File "H:\anaconda3\lib\site-packages\scipy\io\matlab\_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "H:\anaconda3\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "H:\anaconda3\lib\site-packages\scipy\io\matlab\_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "H:\anaconda3\lib\site-packages\scipy\io\matlab\_mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\研究生论文\\OneDrive - stu.hebut.edu.cn\\TATN-main\\normalized_data\\Panasonic 18650PF Data/-10degC.mat'
G:\研究生论文\OneDrive - stu.hebut.edu.cn\TATN-main\normalized_data\Panasonic 18650PF Data/-10degC

**Comment by Xiao-XU-via** [comment]
> H：\anaconda3\python.exe “G：\研究生论文\OneDrive - stu.hebut.edu.cn\TATN-main\normalized_data\process.py” 回溯（最近一次调用最后一次）：文件“H：\anaconda3\lib\site-packages\scipy\io\matlab_mio.py”，第 39 行，_open_file返回 open（file_like， mode），True PermissionError：[Errno 13] 权限被拒绝：“G：\研究生论文\OneDrive - stu.hebut.edu.cn\TATN-main\normalized_data\Panasonic 18650PF Data/-10degC”
> 
> 在处理上述异常的过程中，发生了另一个异常：
> 
> 回溯（最近一次调用最后一次）： 文件“G：\研究生论文\OneDrive - stu.hebut.edu.cn\TATN-main\normalized_data\process.py”，第 154 行，在 read_and_save（path） 中 文件“G：\研究生论文\OneDrive - stu.hebut.edu.cn\TATN-main\normalized_data\process.py”，第 15 行，在read_and_save数据中 = sio.loadmat（文件） 文件“H：\anaconda3\lib\site-packages\scipy\io\matlab_mio.py”，第 225 行，在 loadmat 中，带有 _open_file_context（file_name， appendmat） as f： 文件“H：\anaconda3\lib\contextlib.py”，第 135 行，在 **Enter** 中 return next（self.gen） 文件 “H：\anaconda3\lib\site-packages\scipy\io\matlab_mio.py”，第 17 行，在 _open_file_context f 中，打开 = _open_file（file_like，appendmat，模式） 文件“H：\anaconda3\lib\site-packages\scipy\io\matlab_mio.py”，第 45 行，在_open_file返回 open（file_like， mode）， True FileNotFoundError： [Errno 2] 没有这样的文件或目录： 'G：\研究生论文\OneDrive - stu.hebut.edu.cn\TATN-main\normalized_data\Panasonic 18650PF Data/-10degC.mat' G：\研究生论文\OneDrive - stu.hebut.edu.cn\TATN-main\normalized_data\Panasonic 18650PF Data/-10degC

好想要到那个什么cycle文件里面
